version: '3.4'

services:
  postgres:
    # db with some data from ls5, 7, 8 pre-indexed
    build: docker/db/
    environment:
      - POSTGRES_DB=odc
      - POSTGRES_PASSWORD=odcpass
      - POSTGRES_USER=odcuser
    ports:
      - "5431:5432"
    restart: always
  # Overwrite ows so it can talk to docker db
  coastline:
    build:
      context: .
    links:
      - postgres:postgres
    environment:
      DB_PORT: 5432
      DB_HOSTNAME: postgres
      DB_USERNAME: odcuser
      DB_PASSWORD: odcpass
      DB_DATABASE: odc
    depends_on:
      - postgres
    volumes:
      - ./artifacts:/mnt/artifacts
    command: tail -f /dev/null